export enum MSG_TYPES {
  SELECT_SQUARE = "SELECT_SQUARE",
  UPDATE_CURSOR = "UPDATE_CURSOR",
  READY_PLAYER = "READY_PLAYER",
  SET_ONLINE_NAME = "SET_ONLINE_NAME",
  SWITCH_PLAYER_SYMBOLS = "SWITCH_PLAYER_SYMBOLS"
}